import type { CalculatorDefinition } from "./types";
import { formatNumber } from "@/lib/utils";

export const apiRateLimitCalculator: CalculatorDefinition = {
  slug: "api-rate-limit-calculator",
  title: "API Rate Limit Calculator",
  description: "Free API rate limit calculator. Determine how many API requests you can make per second, minute, or hour. Plan API usage and avoid throttling.",
  category: "Science",
  categorySlug: "science",
  icon: "A",
  keywords: ["api rate limit calculator", "rate limiting", "api throttling", "requests per second", "api quota calculator"],
  variants: [
    {
      id: "rate-planning",
      name: "Rate Limit Planning",
      description: "Calculate request distribution within rate limits",
      fields: [
        { name: "rateLimit", label: "Rate Limit", type: "number", placeholder: "e.g. 1000", min: 1 },
        { name: "period", label: "Per Period", type: "select", options: [
          { label: "Per Second", value: "1" },
          { label: "Per Minute", value: "60" },
          { label: "Per Hour", value: "3600" },
          { label: "Per Day", value: "86400" },
        ], defaultValue: "3600" },
        { name: "totalRequests", label: "Total Requests Needed", type: "number", placeholder: "e.g. 50000", min: 1 },
      ],
      calculate: (inputs) => {
        const rateLimit = inputs.rateLimit as number;
        const period = parseFloat(inputs.period as string) || 3600;
        const totalRequests = inputs.totalRequests as number;
        if (!rateLimit || !totalRequests) return null;

        const requestsPerSecond = rateLimit / period;
        const requestsPerMinute = requestsPerSecond * 60;
        const requestsPerHour = requestsPerSecond * 3600;
        const requestsPerDay = requestsPerSecond * 86400;

        const totalTimeSeconds = totalRequests / requestsPerSecond;
        const totalTimeMinutes = totalTimeSeconds / 60;
        const totalTimeHours = totalTimeSeconds / 3600;

        const minDelayMs = (1 / requestsPerSecond) * 1000;

        return {
          primary: { label: "Time to Complete", value: totalTimeHours >= 1 ? `${formatNumber(totalTimeHours, 1)} hours` : `${formatNumber(totalTimeMinutes, 1)} minutes` },
          details: [
            { label: "Requests/Second", value: formatNumber(requestsPerSecond, 2) },
            { label: "Requests/Minute", value: formatNumber(requestsPerMinute, 0) },
            { label: "Requests/Hour", value: formatNumber(requestsPerHour, 0) },
            { label: "Requests/Day", value: formatNumber(requestsPerDay, 0) },
            { label: "Min Delay Between Requests", value: `${formatNumber(minDelayMs, 0)} ms` },
            { label: "Total Requests Needed", value: formatNumber(totalRequests, 0) },
            { label: "Total Time (seconds)", value: formatNumber(totalTimeSeconds, 0) },
            { label: "Total Time (minutes)", value: formatNumber(totalTimeMinutes, 1) },
            { label: "Total Time (hours)", value: formatNumber(totalTimeHours, 2) },
          ],
        };
      },
    },
    {
      id: "concurrent-users",
      name: "Concurrent User Estimation",
      description: "Estimate API calls generated by concurrent users",
      fields: [
        { name: "users", label: "Concurrent Users", type: "number", placeholder: "e.g. 1000", min: 1 },
        { name: "actionsPerMinute", label: "Actions per User per Minute", type: "number", placeholder: "e.g. 5", min: 0.1, defaultValue: 5 },
        { name: "apiCallsPerAction", label: "API Calls per Action", type: "number", placeholder: "e.g. 3", min: 1, defaultValue: 3 },
        { name: "rateLimit", label: "API Rate Limit (per minute)", type: "number", placeholder: "e.g. 10000", min: 1 },
      ],
      calculate: (inputs) => {
        const users = inputs.users as number;
        const actionsPerMinute = inputs.actionsPerMinute as number;
        const apiCallsPerAction = inputs.apiCallsPerAction as number;
        const rateLimit = inputs.rateLimit as number;
        if (!users || !actionsPerMinute || !apiCallsPerAction || !rateLimit) return null;

        const totalCallsPerMinute = users * actionsPerMinute * apiCallsPerAction;
        const totalCallsPerSecond = totalCallsPerMinute / 60;
        const utilizationPercent = (totalCallsPerMinute / rateLimit) * 100;
        const headroom = rateLimit - totalCallsPerMinute;
        const maxUsers = Math.floor(rateLimit / (actionsPerMinute * apiCallsPerAction));

        return {
          primary: { label: "API Calls/Minute", value: formatNumber(totalCallsPerMinute, 0) },
          details: [
            { label: "Calls per Second", value: formatNumber(totalCallsPerSecond, 1) },
            { label: "Calls per Minute", value: formatNumber(totalCallsPerMinute, 0) },
            { label: "Rate Limit", value: `${formatNumber(rateLimit, 0)}/min` },
            { label: "Utilization", value: `${formatNumber(utilizationPercent, 1)}%` },
            { label: "Headroom", value: headroom >= 0 ? `${formatNumber(headroom, 0)} calls/min` : `Over limit by ${formatNumber(Math.abs(headroom), 0)} calls/min` },
            { label: "Max Supported Users", value: formatNumber(maxUsers, 0) },
            { label: "Status", value: utilizationPercent <= 80 ? "Safe (under 80%)" : utilizationPercent <= 100 ? "Warning (80-100%)" : "Over Limit!" },
          ],
        };
      },
    },
  ],
  relatedSlugs: ["json-size-calculator", "server-bandwidth-calculator", "throughput-calculator"],
  faq: [
    { question: "What is API rate limiting?", answer: "Rate limiting restricts the number of API requests a client can make within a time window. Common limits are 100 requests/minute or 1000 requests/hour. Exceeding the limit typically returns HTTP 429 (Too Many Requests). It protects servers from abuse and ensures fair usage." },
    { question: "How should I handle rate limits in my application?", answer: "Implement exponential backoff (wait 1s, 2s, 4s, etc. on retries), use request queuing, cache responses when possible, batch requests, and monitor your usage. Check response headers like X-RateLimit-Remaining to track your quota." },
  ],
  formula: "Requests/Second = Rate Limit / Period | Total Time = Total Requests / Requests per Second",
};
