import type { CalculatorDefinition } from "./types";
import { formatNumber } from "@/lib/utils";

export const carbonFootprintCalculator: CalculatorDefinition = {
  slug: "carbon-footprint-calculator",
  title: "Carbon Footprint Calculator",
  description: "Free carbon footprint calculator. Estimate your annual CO₂ emissions from driving, electricity, and flights.",
  category: "Everyday",
  categorySlug: "everyday",
  icon: "~",
  keywords: ["carbon footprint calculator", "co2 calculator", "carbon emissions", "carbon offset", "greenhouse gas"],
  variants: [
    {
      id: "driving",
      name: "Driving Emissions",
      fields: [
        { name: "miles", label: "Annual Miles Driven", type: "number", placeholder: "e.g. 12000" },
        { name: "mpg", label: "Fuel Efficiency (MPG)", type: "number", placeholder: "e.g. 25" },
        {
          name: "fuel", label: "Fuel Type", type: "select",
          options: [
            { label: "Gasoline", value: "gas" },
            { label: "Diesel", value: "diesel" },
          ],
        },
      ],
      calculate: (inputs) => {
        const miles = inputs.miles as number, mpg = inputs.mpg as number;
        const fuel = (inputs.fuel as string) || "gas";
        if (!miles || !mpg) return null;
        const gallons = miles / mpg;
        const co2PerGallon = fuel === "diesel" ? 22.44 : 19.6;
        const totalLbs = gallons * co2PerGallon;
        const totalTons = totalLbs / 2204.6;
        return {
          primary: { label: "Annual CO₂", value: `${formatNumber(totalTons, 2)} metric tons` },
          details: [
            { label: "CO₂ in lbs", value: `${formatNumber(totalLbs, 0)} lbs` },
            { label: "Gallons used", value: formatNumber(gallons, 0) },
            { label: "CO₂ per mile", value: `${formatNumber(totalLbs / miles, 2)} lbs` },
          ],
        };
      },
    },
    {
      id: "electricity",
      name: "Electricity Emissions",
      fields: [
        { name: "kwh", label: "Monthly kWh Usage", type: "number", placeholder: "e.g. 900" },
      ],
      calculate: (inputs) => {
        const kwh = inputs.kwh as number;
        if (!kwh) return null;
        const annualKwh = kwh * 12;
        const co2Lbs = annualKwh * 0.92;
        const co2Tons = co2Lbs / 2204.6;
        return {
          primary: { label: "Annual CO₂", value: `${formatNumber(co2Tons, 2)} metric tons` },
          details: [
            { label: "Annual kWh", value: formatNumber(annualKwh, 0) },
            { label: "CO₂ in lbs", value: `${formatNumber(co2Lbs, 0)} lbs` },
          ],
        };
      },
    },
    {
      id: "flight",
      name: "Flight Emissions",
      fields: [
        { name: "miles", label: "Flight Distance (miles, one way)", type: "number", placeholder: "e.g. 2500" },
        { name: "roundTrip", label: "Round Trip?", type: "select", options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }] },
        { name: "trips", label: "Number of Trips per Year", type: "number", placeholder: "e.g. 2", defaultValue: 1 },
      ],
      calculate: (inputs) => {
        const dist = inputs.miles as number;
        const rt = (inputs.roundTrip as string) || "yes";
        const trips = (inputs.trips as number) || 1;
        if (!dist) return null;
        const totalMiles = dist * (rt === "yes" ? 2 : 1) * trips;
        const co2Lbs = totalMiles * 0.53;
        const co2Tons = co2Lbs / 2204.6;
        return {
          primary: { label: "Annual CO₂ from Flights", value: `${formatNumber(co2Tons, 2)} metric tons` },
          details: [
            { label: "Total flight miles", value: formatNumber(totalMiles, 0) },
            { label: "CO₂ in lbs", value: `${formatNumber(co2Lbs, 0)} lbs` },
          ],
        };
      },
    },
  ],
  relatedSlugs: ["gas-mileage-calculator", "electricity-cost-calculator", "fuel-cost-calculator"],
  faq: [{ question: "What is a carbon footprint?", answer: "A carbon footprint is the total amount of greenhouse gases (CO₂) generated by your actions. The average American produces about 16 metric tons of CO₂ per year. Globally, the average is about 4 tons." }],
  formula: "Driving: (miles/MPG) × CO₂/gallon | Electricity: kWh × 0.92 lbs CO₂",
};
