import type { CalculatorDefinition } from "./types";
import { formatNumber } from "@/lib/utils";

export const torusVolumeCalculator: CalculatorDefinition = {
  slug: "torus-volume-calculator",
  title: "Torus Volume Calculator",
  description: "Free torus volume calculator. Calculate the volume and surface area of a torus from major and minor radii.",
  category: "Math",
  categorySlug: "math",
  icon: "+",
  keywords: ["torus volume calculator", "torus calculator", "volume of torus", "torus surface area", "donut shape calculator"],
  variants: [
    {
      id: "fromRadii",
      name: "From Major & Minor Radius",
      fields: [
        { name: "R", label: "Major Radius (R) - center to tube center", type: "number", placeholder: "e.g. 10" },
        { name: "r", label: "Minor Radius (r) - tube radius", type: "number", placeholder: "e.g. 3" },
      ],
      calculate: (inputs) => {
        const R = inputs.R as number, r = inputs.r as number;
        if (!R || !r || r >= R) return null;
        const volume = 2 * Math.PI * Math.PI * R * r * r;
        const surfaceArea = 4 * Math.PI * Math.PI * R * r;
        const outerRadius = R + r;
        const innerRadius = R - r;
        return {
          primary: { label: "Volume", value: formatNumber(volume, 6) },
          details: [
            { label: "Surface area", value: formatNumber(surfaceArea, 6) },
            { label: "Outer radius", value: formatNumber(outerRadius, 6) },
            { label: "Inner radius", value: formatNumber(innerRadius, 6) },
            { label: "Major radius (R)", value: formatNumber(R, 6) },
            { label: "Minor radius (r)", value: formatNumber(r, 6) },
          ],
        };
      },
    },
    {
      id: "fromOuterInner",
      name: "From Outer & Inner Radius",
      fields: [
        { name: "outer", label: "Outer Radius", type: "number", placeholder: "e.g. 13" },
        { name: "inner", label: "Inner Radius", type: "number", placeholder: "e.g. 7" },
      ],
      calculate: (inputs) => {
        const outer = inputs.outer as number, inner = inputs.inner as number;
        if (!outer || !inner || inner >= outer) return null;
        const R = (outer + inner) / 2;
        const r = (outer - inner) / 2;
        const volume = 2 * Math.PI * Math.PI * R * r * r;
        const surfaceArea = 4 * Math.PI * Math.PI * R * r;
        return {
          primary: { label: "Volume", value: formatNumber(volume, 6) },
          details: [
            { label: "Surface area", value: formatNumber(surfaceArea, 6) },
            { label: "Major radius (R)", value: formatNumber(R, 6) },
            { label: "Minor radius (r)", value: formatNumber(r, 6) },
          ],
        };
      },
    },
  ],
  relatedSlugs: ["sphere-calculator", "cylinder-volume-calculator", "cone-volume-calculator"],
  faq: [
    { question: "How do you calculate the volume of a torus?", answer: "Volume = 2*pi^2*R*r^2, where R is the major radius (center of torus to center of tube) and r is the minor radius (tube radius)." },
    { question: "What is a torus?", answer: "A torus is a donut-shaped surface of revolution generated by revolving a circle about an axis coplanar with the circle that does not intersect it." },
  ],
  formula: "V = 2*pi^2*R*r^2 | SA = 4*pi^2*R*r",
};
